ruby "2.3.1"

source "https://rubygems.org"

gem "sinatra", "~>1.4.7"
gem "sinatra-contrib"
gem "erubis"
gem "minitest"
gem "pry"
gem "bcrypt"
gem "twilio-ruby"
gem "rufus-scheduler"

group :production do
  gem "puma"
end